### ISSUE TITLE
Unable to run coc-elixir after upgrading to 0.5

### ISSUE THREAD

**Issue by heimann** [elixir-lsp/coc-elixir#25]
The language server won't start. I've tested cleaning out deps, re-installing etc but still not able to get it to run.

Stacktrace:
`** (UndefinedFunctionError) function ElixirLS.LanguageServer.CLI.main/0 is undefined (module ElixirLS.LanguageServer.CLI is not available) ElixirLS.LanguageServer.CLI.main() `

**Comment by heimann** [comment]
Turns out the solution is to compile and run coc-elixir with 1.10.4 and OTP 23. Failed with OTP 22.

**Comment by amiralies** [comment]
yea in case you can't install newer otp or elixir you can build elixir-ls from source and use `"elixir.pathToElixirLS"` option. It might be good idea if I build packaged elixir-ls with lower otp / elixir versoin
