### ISSUE TITLE
The elixir server crashed 5 times in last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by collegeimprovements** [elixir-lsp/coc-elixir#29]
I'm getting the following error message in neovim.
`The elixir server crashed 5 times in last 3 minutes. The server will not be restarted.`

And hence i'm not able to use it.
What can i try to fix it ?

**Comment by amiralies** [comment]
Can you try with [manual](https://github.com/elixir-lsp/coc-elixir#server-fails-to-start) elixir-ls installation?

**Comment by collegeimprovements** [comment]
@amiralies It works. Thanks a lot 😊

**Comment by cognociente** [comment]
I am having the exact same error in Visual Studio Code.

**Comment by amiralies** [comment]
@cognociente Check this section https://github.com/elixir-lsp/vscode-elixir-ls#troubleshooting, if you still had problems open an issue on elixir-lsp/vscode-elixir-ls repo.
