### ISSUE TITLE
Error to start when version of projects are different

### ISSUE THREAD

**Issue by basmoura** [elixir-lsp/coc-elixir#36]
Hi. 

I'm getting the error `The elixir server crashed 5 times in last 3 minutes. The server will not be restarted.` every time I open a project with different versions of the Elixir and Erlang that I compiled my ElixirLS.

I compiled my ElixirLS using `Erlang 23.0.4` and `Elixir 1.10.4-otp-23` and when I open NeoVim with an project using older version of like Erlang 22 and/or Elixir 1.7 the error of elixir crashed is returned.

For my projects with `Erlang 23.0.4` and `Elixir 1.10.4-otp-23` works great.

How could I build the ElixirLS be working with all versions?

**Comment by amiralies** [comment]
Minimum [supported](https://github.com/elixir-lsp/elixir-ls#supported-versions) versions by elixir-ls are `Elixir 1.8.0` and `OTP 21`,
I think compiling elixir-ls with these versions should be fine for any project with supported versions.

**Comment by basmoura** [comment]
thanks @amiralies, I will try with this versions
