### ISSUE TITLE
How do you autoformat eelixir files ?

### ISSUE THREAD

**Issue by aswinmohanme** [elixir-lsp/coc-elixir#37]
This awesome library made me switch from Spacemacs to Neovim :+1: . Everything is working fine, but I have one issue.

What do you use for autoformatting `eelixir` or `.eex` files ? I have tried a bunch of plugins and none seem to work. Any pointers will be much appreciated.

Thanks

**Comment by onixus74** [comment]
I use a forked version of [htmlbeautifier](https://github.com/threedaymonk/htmlbeautifier) with [vim-autoformat](https://github.com/vim-autoformat/vim-autoformat)

**Comment by ghost** [comment]
@aswinmohanme 

Something like `autocmd BufWritePost *.html.heex !mix format <afile>` should work

**Comment by adamu** [comment]
I believe elixir-ls supports eex/heex, so shouldn't coc-elixir also use the language server for `eelixir` files?
