### ISSUE TITLE
Add end after opening do block

### ISSUE THREAD

**Issue by aswinmohanme** [elixir-lsp/coc-elixir#45]
There is a plugin that already does it `tpope/vim-endwise` but it is buggy and has conflicts with`coc-elixir`.  It would be really nice if `coc-elixir` could support this natively. 

Also really great and awesome plugin. Works everywhere else like a charm 👍

**Comment by amiralies** [comment]
Hi,
coc-elixir is a actually a think layer on top of elixir-ls and it tries to connect to elixir-ls smoothly, this kinda features are not likely to be implemented in coc-elixir (maybe we can have this as a snippet in elixir-ls itself). what about using custom snippets? I use [coc-snippets](https://github.com/neoclide/coc-snippets) with [vim-snippets ](https://github.com/honza/vim-snippets), there's [do/end](https://github.com/honza/vim-snippets) snippet.

**Comment by aswinmohanme** [comment]
Makes sense, I'll try that thanks.
