### ISSUE TITLE
Fails to lint/run diagnostics on larger projects

### ISSUE THREAD

**Issue by natdm** [elixir-lsp/coc-elixir#59]
I've got the following plugins installed:

```
Plug 'elixir-editors/vim-elixir'
Plug 'elixir-lsp/coc-elixir', {'do': 'yarn install && yarn prepack'}
```

I also have the following code in two reps -- one is a small app I made with mix, the other has many many files (over 2k `.ex$` files, plus js). 

```elixir
  def foo(a) do
    5
  end
```

The smaller project will show the unused parameter warning, while the larger one does not. Goto def, formatting, docs, etc, all work -- but it looks like diagnostics may not be working. How do I troubleshoot this?

Node: 12.6.3
NVIM: 0.5.0
Latest for all plugins, as of today.
No warnings in `chechealth: provider`

**Comment by amiralies** [comment]
Can you try that on vscode to check if it works? it might be an issue with language server and not related to this extensions directly.

**Comment by natdm** [comment]
> Can you try that on vscode to check if it works? it might be an issue with language server and not related to this extensions directly.

Good question. It seems to behave the exact same on vscode.

**Comment by natdm** [comment]
Closing, looks like coc-elixir is good to go here. Problem is elsewhere.

**Comment by amiralies** [comment]
Can you open an issue in [elixir-lsp/elixir-ls ](https://github.com/elixir-lsp/elixir-ls)?
